# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev

pool:
  name: Default

steps:
- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '$(Build.SourcesDirectory)'
    FodConnection: 'FOD-FranklinBank24'
    ReleaseOptions: '0'
    ReleaseId: 1105947
    EntitlementSelection: '0'
    Entitlement: 12880
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'mvn'
    BuildCommand: 'clean install -DskipTests=true dependency:tree -DoutputFile=debricked-maven-dependencies.tgf -DoutputType=tgf'
    BuildFile: 'pom.xml'
    PolicyFailAction: '0'